# Generated by Django 4.0.2 on 2022-06-09 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_create',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='news.categoryarticle', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Last change'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_field',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publisher', 'Publisher')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='categoryarticle',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='categoryarticle',
            name='name_category',
            field=models.CharField(max_length=30, verbose_name='Name tags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.article', verbose_name='Related article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Text comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name user'),
        ),
    ]
